version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: takewalk_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uomdiss1131
      POSTGRES_DB: takewalk
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data